routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/', function () {
//     return view('welcome');
// });
Auth::routes();
Route::get('/', 'PostController@index')->name('posts.index');
Route::get('/posts/search', 'PostController@search')->name('posts.search');
Route::resource('/posts', 'PostController',  ['except' => ['index']]);
Route::resource('/users', 'UserController');
Route::resource('/comments', 'CommentController')->middleware('auth');

app/Post.php
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class Post extends Model
{
    protected $fillable = [
        'user_id', 'category_id', 'content', 'title','image'
    ];
    public function category(){
      // 投稿は1つのカテゴリーに属する
      return $this->belongsTo(\App\Category::class,'category_id');
    }
    public function user(){
      return $this->belongsTo(\App\User::class,'user_id');
    }
    public function comments(){
      return $this->hasMany(\App\Comment::class,'post_id', 'id');
    }
    public function tags()
    {
        return $this->belongsToMany('App\Tag')->withTimestamps();
    }
}

app/Http/Controllers/PostController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Http\Requests\PostReuest;
use App\Post;
use App\Tag;
class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $q = \Request::query();
        if(isset($q['category_id'])){
            $posts = Post::latest()->where('category_id', $q['category_id'])->paginate(3);
            $posts->load('category', 'user', 'tags');
            return view('posts.index', [
                'posts' => $posts,
                'category_id' => $q['category_id']
            ]);
        } if(isset($q['tag_name'])){
            $posts = Post::latest()->where('content', 'like', "%{$q['tag_name']}%")->paginate(3);
            $posts->load('category', 'user', 'tags');
            return view('posts.index', [
                'posts' => $posts,
                'tag_name' => $q['tag_name']
            ]);
        }else {
            $posts = Post::latest()->paginate(3);
            $posts->load('category', 'user', 'tags');
            return view('posts.index', [
                'posts' => $posts,
            ]);
        }
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create', [
        ]);
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
   public function store(PostReuest $request)
    {
        if($request->file('image')->isValid()) {
            $post = new Post;
            // $input = $request->only($post->getFillable());
            $post->user_id = $request->user_id;
            $post->category_id = $request->category_id;
            $post->content = $request->content;
            $post->title = $request->title;
            $filename = $request->file('image')->store('public/image');
            $post->image = basename($filename);
            // contentからtagを抽出
            preg_match_all('/#([a-zA-Z0-9０-９ぁ-んァ-ヶー一-龠]+)/u', $request->content, $match);
            $tags = [];
            foreach ($match[1] as $tag) {
                $found = Tag::firstOrCreate(['tag_name' => $tag]);
                array_push($tags, $found);
            }
            $tag_ids = [];
            foreach ($tags as $tag) {
                array_push($tag_ids, $tag['id']);
            }
            $post->save();
            $post->tags()->attach($tag_ids);
        }
        return redirect('/');
    }

    
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        $post->load('category', 'user', 'comments.user');
        return view('posts.show', [
            'post' => $post,
        ]);
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function search(Request $request)
    {
        $posts = Post::where('title', 'like', "%{$request->search}%")
                ->orWhere('content', 'like', "%{$request->search}%")
                ->paginate(3);
        $search_result = $request->search.'の検索結果'.$posts->total().'件';
        return view('posts.index', [
            'posts' => $posts,
            'search_result' => $search_result,
            'search_query'  => $request->search
        ]);
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card-header">投稿一覧</div>
<div class="card-body">
    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif

        <div class="card">
          <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}

              <div class="form-group">
                <label for="exampleInputEmail1">タイトル</label>
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="title" name="title">
              </div>

              <div class="form-group">
                <label for="exampleFormControlFile1">画像選択</label>
                <input type="file" class="form-control-file" id="exampleFormControlFile1" name="image">
              </div>

               <div class="form-group">
                    <label for="exampleFormControlSelect1">カテゴリー</label>
                    <select class="form-control" id="exampleFormControlSelect1" name="category_id">
                        <option selected="">選択する</option>
                        <option value="1">占い師</option>
                        <option value="2">霊能者</option>
                        <option value="3">狩人</option>
                        <option value=4">市民</option>
                        <option value="5">狂人</option>
                        <option value="6">人狼</option>
                        
                    </select>
                </div>

                <div class="form-group">
                  <label for="comment">内容　:#〇〇があるとタグとして検索できます(例：#占い師)</label>
                  <textarea class="form-control" rows="5" id="comment" name="content"></textarea>
                </div>

                <input type="hidden" name="user_id" value="{{ Auth::id() }}">

              <button type="submit" class="btn btn-primary">投稿する</button>
            </form>
          </div>
        </div>
</div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="card-body">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h5 class="card-title">タグ検索フォーム</h5>
                <div id="custom-search-input">
                    <div class="input-group col-md-12">
                        <form action="{{ route('posts.search') }}" method="get">

                            <input type="text" class="form-control input-lg" placeholder="" name="search" value="">
                            <span class="input-group-btn" style="position: relative;top: -36px;right: -179px;">
                                <button class="btn btn-info" type="submit">
                                    <i class="fas fa-search"></i>
                                </button>
                            </span>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="card-header">投稿一覧</div>

@isset($search_result)
    <h5 class="card-title">{{ $search_result }}</h5>
@endisset

<div class="card-body">
    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif

    @foreach($posts as $post)
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ $post->title }}</h5>
            <h5 class="card-title">
                カテゴリー:
                 <a href="{{ route('posts.index', ['category_id' => $post->category_id]) }}">
                    {{ $post->category->category_name }}
                </a>
            </h5>

            <h5 class="card-title">
                Tag:
                @foreach($post->tags as $tag)
                    <a href="{{ route('posts.index', ['tag_name' => $tag->tag_name]) }}">
                        #{{ $tag->tag_name }}
                    </a>
                @endforeach
            </h5>
            <h5 class="card-title">
                投稿者:
                <a href="{{ route('users.show', $post->user_id) }}">{{ $post->user->name }}</a>
            </h5>
            <p class="card-text">{{ $post->content }}</p>
            <a href="{{ route('posts.show', $post->id) }}" class="btn btn-primary">詳細</a>
          </div>
        </div>
    @endforeach


@if(isset($category_id))
    {{ $posts->appends(['category_id' => $category_id])->links() }}

@elseif(isset($tag_name))
    {{ $posts->appends(['tag_name' => $tag_name])->links() }}

@elseif(isset($search_query))
    {{ $posts->appends(['search' => $search_query])->links() }}

@else
    {{ $posts->links() }}
@endif



</div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
<div class="card-header">投稿一覧</div>
<div class="card-body">
    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif

        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ $post->title }}</h5>
            <h5 class="card-title">
                カテゴリー:{{ $post->category->category_name }}
            </h5>
            <h5 class="card-title">
                投稿者:{{ $post->user->name }}
            </h5>
            <p class="card-text">{{ $post->content }}</p>
            <img src="{{ asset('storage/image/'.$post->image) }}">
          </div>
        </div>

       <div class="p-3">
        <h3 class="card-title">コメント一覧</h3>
        @foreach($post->comments as $comment)
            <div class="card">
                <div class="card-body">
                    <p class="card-text">{{ $comment->comment }}</p>
                    <p class="card-text">
                        投稿者:
                        <a href="{{ route('users.show', $comment->user->id) }}">
                            {{ $comment->user->name }}
                        </a>
                    </p>
                </div>
            </div>
        @endforeach
        <a href="{{ route('comments.create', ['post_id' => $post->id]) }}" class="btn btn-primary">コメントする</a>
    </div>
</div>
@endsection